# Generated by Django 3.2.5 on 2021-07-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nit',
            field=models.CharField(default='0', max_length=14),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
